### ISSUE TITLE
[Feature Request]: Little endian binary file support

### ISSUE THREAD

**Issue by veprbl** [pylhc/sdds#47]
### Feature Description

The current test covers the big endian binary file `tests/inputs/test_file.sdds`, would be nice if little-endian files were supported too.

The current behavior is to crash while trying to read a string of incorrect length:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "$prefix/lib/python3.9/site-packages/sdds/reader.py", line 29, in read_sdds
    data_list = _read_data(data, definition_list, inbytes)
  File "$prefix/lib/python3.9/site-packages/sdds/reader.py", line 89, in _read_data
    return _read_data_binary(definitions, inbytes)
  File "$prefix/lib/python3.9/site-packages/sdds/reader.py", line 107, in _read_data_binary
    return [functs_dict[definition.__class__](inbytes, definition) for definition in definitions]
  File "$prefix/lib/python3.9/site-packages/sdds/reader.py", line 107, in <listcomp>
    return [functs_dict[definition.__class__](inbytes, definition) for definition in definitions]
  File "$prefix/lib/python3.9/site-packages/sdds/reader.py", line 120, in _read_bin_param
    return inbytes.read(str_len).decode(ENCODING)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xee in position 20: invalid continuation byte
```

**Comment by veprbl** [comment]
A workaround is to convert the input files using the "sddsendian" (https://ops.aps.anl.gov/manuals/SDDStoolkit/SDDStoolkitsu37.html)

**Comment by JoschD** [comment]
Hello @veprbl !
Thank you very much for your feature request.
I think the reason we don't have little-endian files, is because we have not encountered them yet.
Could you maybe provide an example file to test on?

At a quick glance, you might be able to do a quick check on your end by switching 
"long" to "short" in https://github.com/pylhc/sdds/blob/fa613dbe4621030c5d342e1acabe787fd7b8c68a/sdds/reader.py#L160

Let me know if this works.

Cheers,
Joschua

**Comment by JoschD** [comment]
Hello again,

sorry, my understanding of endianness has increased over the last few minutes and my original suggestion is not at all useful.

One probably needs to do something like `struct.unpack("<s", inbytes.read(str_length))` where `<` is little endian, and `>` is big endian. 

But an example file would be really helpful.

Cheers,
Joschua

**Comment by veprbl** [comment]
For some reason your original test_file.sdds doesn't cause the crash when converted to big-endian. I had to add a string parameter to it (converted to ascii, edited, converted back), and now it triggers the crash:
[test_file.sdds.gz](https://github.com/pylhc/sdds/files/8645342/test_file.sdds.gz)

**Comment by JoschD** [comment]
Hey @veprbl ,
I created a new branch https://github.com/pylhc/sdds/tree/support_little_endian that should allow you to read little-endian files. It would be very kind if you could test that this works for your usecases, before we do a release. I tested it on the file you provided, which seems to run fine. 

An interesting test would also be, to use `sdds.write()` to write from a `little-endian` machine and read it on a `big-endian` machine. It should only write in `big-endian` order, at least for the data, but I am not 100% sure about the header.
If you could test this, that would be amazing. 

Cheers,

Joschua
